# Generated by Django 5.0.1 on 2024-02-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
