# Generated by Django 5.0.1 on 2024-02-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0004_customuser_is_cater_customuser_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cata_images'),
        ),
    ]
