# Generated by Django 4.1.5 on 2024-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caterapp', '0007_buynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
